export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const OPEN_REGISTER_MODAL = "OPEN_REGISTER_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const CLOSE_REGISTER_MODAL = "CLOSE_REGISTER_MODAL";
export const REMOVE_SUCCESS_MSG = "REMOVE_SUCCESS_MSG";
export const REMOVE_POST_MSG = "REMOVE_POST_MSG";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_FAIL = "DELETE_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const LOADING = "LOADING";
export const LOADING_POSTS = "LOADING_POSTS";

export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const GET_USER_INFO = "GET_USER_INFO";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const EDIT_POST = "EDIT_POST";
export const POST_ERROR = "POST_ERROR";

export const SHOW_COMMENTS = "SHOW_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const COMMENT_ERROR = "COMMENT_ERROR";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";

export const RESET_POSTS = "RESET_POSTS";
export const RESET_AUTH = "RESET_AUTH";
export const SET_ALERT = "SET_ALERT";

export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const UPDATE_LIKES = "UPDATE_LIKES";
